jwt:
   secret: 'av#è-787hgytuithuvAZERTYUIbdfnrHHBd74555;,!!§§11&&&q*+°°ù*µ&aQSDVIJKLDA147100ASQCB12&ç_ç? hdhdjdhfhsvcgdg7458jdbcvqhwdfsderetdghhhhfhbdgggdé"""-'

server:
  port: 8095
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app_livraison 
    password: 12345 
    username: root 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect